language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - sudo apt-get install -y binutils libproj-dev gdal-bin libsqlite3-mod-spatialite
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
install:
  - pip install .
# command to run tests
script:
  - pytest
  - cd tests/django_test ; python manage.py test testapp
